"""adding changing password to password_hash

Revision ID: 14904e182f28
Revises: c6a092b8a044
Create Date: 2017-04-20 12:58:58.032476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14904e182f28'
down_revision = 'c6a092b8a044'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hash', sa.String(length=128), nullable=True))
    op.create_unique_constraint(None, 'user', ['username'])
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'password_hash')
    # ### end Alembic commands ###
